const typography = {
  head1: {
    fontFamily: 'Pretendard Variable',
    fontSize: '40px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '150%',
    letterSpacing: '-0.005em',
  },
  head2: {
    fontFamily: 'Pretendard Variable',
    fontSize: '36px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '150%',
    letterSpacing: '-0.005em',
  },
  head3: {
    fontFamily: 'Pretendard Variable',
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '150%',
    letterSpacing: '-0.005em',
  },
  head4: {
    fontFamily: 'Pretendard Variable',
    fontSize: '28px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '150%',
    letterSpacing: '-0.005em',
  },
  head5: {
    fontFamily: 'Pretendard Variable',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '150%',
    letterSpacing: '-0.005em',
  },
  title1: {
    fontFamily: 'Pretendard Variable',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '150%',
  },
  title2: {
    fontFamily: 'Pretendard Variable',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '150%',
  },
  title3: {
    fontFamily: 'Pretendard Variable',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '150%',
  },
  title4: {
    fontFamily: 'Pretendard Variable',
    fontSize: '15px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '150%',
  },
  title5: {
    fontFamily: 'Pretendard Variable',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '150%',
  },
  body1R: {
    fontFamily: 'Pretendard Variable',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '150%',
    letterSpacing: '-0.025em',
  },
  body2R: {
    fontFamily: 'Pretendard Variable',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '150%',
    letterSpacing: '-0.025em',
  },
  body3R: {
    fontFamily: 'Pretendard Variable',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '150%',
    letterSpacing: '-0.025em',
  },
  body4R: {
    fontFamily: 'Pretendard Variable',
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '150%',
    letterSpacing: '-0.025em',
  },
  body1M: {
    fontFamily: 'Pretendard Variable',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '150%',
    letterSpacing: '-0.025em',
  },
  body2M: {
    fontFamily: 'Pretendard Variable',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '150%',
    letterSpacing: '-0.025em',
  },
  body3M: {
    fontFamily: 'Pretendard Variable',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '150%',
    letterSpacing: '-0.025em',
  },
  body4M: {
    fontFamily: 'Pretendard Variable',
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '150%',
    letterSpacing: '-0.025em',
  },
  button1: {
    fontFamily: 'Pretendard Variable',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '150%',
    letterSpacing: '-0.025em',
  },
  button2: {
    fontFamily: 'Pretendard Variable',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '150%',
    letterSpacing: '-0.025em',
  },
  button3: {
    fontFamily: 'Pretendard Variable',
    fontSize: '13px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '150%',
    letterSpacing: '-0.025em',
  },
  caption1: {
    fontFamily: 'Pretendard Variable',
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '150%',
    letterSpacing: '-0.025em',
  },
  caption2: {
    fontFamily: 'Pretendard Variable',
    fontSize: '10px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '150%',
    letterSpacing: '-0.025em',
  },
};

export default typography;
